Rebase rvh squash 0912
OpenXiangShan/GEM5 pull request #171
Opened 2024-09-12 13:19 UTC by jueshiwenli

2024-09-13 01:07 UTC, lqr8 approved these changes

2024-09-13 06:20 UTC, shinezyy requested changes

2024-09-13 06:20 UTC, shinezyy commented on src/arch/riscv/regs/misc.hh
> -                            STATUS_UIE_MASK;
Delete old code?

2024-09-13 06:20 UTC, shinezyy commented on src/arch/riscv/isa/formats/standard.isa
> +            ((csr <CSR_HSTATUS) ||(csr >CSR_HGATP)) && ((csr <CSR_VSSTATUS) ||(csr > CSR_VSATP))) {
format thiese two line of code?

`csr <CSR_HSTATUS --> csr < CSR_HSTATUS`
`) ||( --> ) || (`

2024-09-13 06:20 UTC, shinezyy commented on src/cpu/base.cc
> +        }
Can we rewrite this chunk of code with a function, a template function, or a macro?

It looks too redundant

2024-09-13 06:20 UTC, shinezyy commented on src/cpu/base.hh
> +        bool errorCsrsValue[36];// CsrRegIndex
Can we use a enum or macro here?

2024-09-13 06:20 UTC, shinezyy commented on src/arch/riscv/isa/decoder.isa
> +                            bool writeSign = false;
local_variable should use snake_case

2024-09-13 06:20 UTC, shinezyy commented on src/arch/riscv/faults.cc
> +            }
the if block and else block seems to be the same?

2024-09-13 10:04 UTC, shinezyy requested changes

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +        else if ((translateMode == twoStageMode) && (!inGstage)){
} else if {

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +        else{
} else if {

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +    }
Are if block and else block the same?

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +            assert(0);
`assert (vsatp.mode != 0);`

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +        assert(0);
`asssert (virt != 0);`

2024-09-13 10:04 UTC, shinezyy commented on src/cpu/o3/lsq_unit.cc
> +        //    RiscvISA::ExceptionCode::LOAD_ADDR_MISALIGNED);
remove them?

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +        } else if (((mode == BaseMMU::Execute) || (isHInst)) && (!pte.x)) {
redundant () ?

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/faults.cc
> +                      tc->setMiscReg(MISCREG_HTVAL, 0);
This code block is large, consider to add { } to avoid confusion

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +        assert(0);
consider to change above two assertions into assert (xxx conditions)

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +                        assert(0);
change to assert (xx condition)

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/isa.cc
> +    }
Can we rewrite above code like:

if (v == 1) and miscreg in [MISCREG_SATP, MISCREG_SPEC ....]:
   return ....

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +            if ((gPaddr & ~(((int64_t)1 << 41) - 1)) != 0) {
change assertion into assert(condition)

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +                            assert(0);
change assertion into assert(condition)

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +                        assert(0);
change assertion into assert(condition)

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +                vaddr = r.req->getPC();
Either  use { } or not use { }. Don't mix them up in a code block.

XS-GEM5 always expected { } even if a block only has one line

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +{
assert hgatp.mode == 8 ?

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +                put_level = level;
std::max?

2024-09-13 10:04 UTC, shinezyy commented on src/cpu/o3/commit.cc
> +            inst_fault->exception() == RiscvISA::ExceptionCode::STOREG_PAGE)
put them in a set, then check whether exception is in this set?

2024-09-13 10:04 UTC, shinezyy commented on src/cpu/o3/commit.cc
> +                exception_no == RiscvISA::ExceptionCode::STOREG_PAGE) {
simliar to above

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +        continuePtw = true;
???

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +                fault = createPagefault(vaddr, 0, mode, false);
add  { }

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +            else{
} else {

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +        else{
} else {

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +                        else if (l2_level == 1)  // hit level =1
add { }

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/pagetable_walker.cc
> +                                                     gstage);
add { }

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +                        lookupL2TLB(vpn + step * i, entry.asid, BaseMMU::Read, true, choose, false, translateMode);
add { }

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +            }
There should be a function, and call this function 4 times

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +            }
There should be a function, and call this function 4 times

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
>          }
There should be a function, and call this function x times.

2024-09-13 10:04 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +        l2tlb = static_cast<TLB *>(nextLevel());
add  { }

2024-09-25 03:00 UTC, shinezyy commented on src/arch/riscv/faults.cc
> +            }
not resolved yet

2024-09-27 03:02 UTC, shinezyy commented on src/arch/riscv/tlb.cc
> +    }
not resolved yet @jueshiwenli

2024-10-08 02:18 UTC, shinezyy approved these changes

2024-10-08 02:24 UTC, merged