mem: fix bugs of xsstream & enable it in kmh_align
OpenXiangShan/GEM5 pull request #197
Opened 2024-10-31 10:49 UTC by jueshiwenli

Change-Id: Ifd6bf72503a2466d18a987680412f83140c8de64

2024-11-01 01:50 UTC, shinezyy requested changes

2024-11-01 01:50 UTC, shinezyy commented on src/mem/cache/prefetch/xs_stream.cc
> +    stream_array.insertEntry(regionHashTag(vaddr_tag_num),secure,entry);
, secure, entry

remember to format code

2024-11-11 09:42 UTC, tastynoob approved these changes

2024-11-12 03:38 UTC, shinezyy approved these changes

2024-11-12 03:41 UTC, merged