Reg arbitration
OpenXiangShan/GEM5 pull request #199
Opened 2024-11-01 08:47 UTC by tastynoob

2024-11-01 08:59 UTC, shinezyy commented
Can you provide the performance impact of this patch here?

2024-11-01 09:47 UTC, tastynoob commented
![image](https://github.com/user-attachments/assets/c2d772cf-5e4c-4165-96ee-6f160283644d)

2024-11-02 06:25 UTC, shinezyy commented
> ![image](https://private-user-images.githubusercontent.com/59657499/382246717-c2d772cf-5e4c-4165-96ee-6f160283644d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjg4OTEsIm5iZiI6MTczMDUyODU5MSwicGF0aCI6Ii81OTY1NzQ5OS8zODIyNDY3MTctYzJkNzcyY2YtNWU0Yy00MTY1LTk2ZWUtNmYxNjAyODM2NDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA2MjMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5N2RhODg4MzVhN2ZjMzI2OWQ2ZmIyNGViZDQ3YzNkOTI2MTMwMzIwYWYxOTg1YzQzYjY2N2NkMjc4ZTc4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SPwTf5eUs1CFB4OTiL1t_zqc2aLxcZTQj4kLOyrfF6U)

This is performance gap, but not the impact of this patch.
The impact of this patch means comparison between two GEM5 versions

2024-11-04 07:53 UTC, tastynoob commented
![image](https://github.com/user-attachments/assets/ef8c4b44-ada7-49b8-9373-b2ef9742b841)
disable prefetcher compare

2024-11-08 03:31 UTC, shinezyy requested changes

2024-11-08 03:31 UTC, shinezyy commented on src/cpu/o3/issue_queue.cc
> +// rftpi = regfile typeid + portid
tpi seems to be strange.

TyPoID? or full name: typePortID

2024-11-08 03:31 UTC, shinezyy commented on src/cpu/o3/issue_queue.cc
> +    // scheduler->addToFU(inst);
remove useless code

2024-11-08 03:31 UTC, shinezyy commented on src/cpu/o3/issue_queue.cc
> +    full |= replayQ.size() > 32;  // TODO: parameterize it
Plz finish todo here

2024-11-08 03:31 UTC, shinezyy commented on src/cpu/o3/issue_queue.cc
> +    std::vector<int> rfportChecker(64, 0);
The meaning of 64? add comments or replace it with constants

2024-11-08 03:31 UTC, shinezyy commented on src/cpu/o3/issue_queue.cc
> +    assert(maxTPI <= 64);
The meaning of 64? add comments or replace it with constants

2024-11-08 03:31 UTC, shinezyy commented on src/cpu/o3/issue_queue.cc
> +        }
Can we use `const auto &` here?

2024-11-08 04:54 UTC, tastynoob commented on src/cpu/o3/issue_queue.cc
> +// rftpi = regfile typeid + portid
how about "TyPI"

2024-11-08 06:34 UTC, tastynoob commented on src/cpu/o3/issue_queue.cc
> +    full |= replayQ.size() > 32;  // TODO: parameterize it
Maybe remove this future

2024-11-08 07:19 UTC, shinezyy approved these changes

2024-11-11 09:38 UTC, merged