basic implement for estride value predictor
OpenXiangShan/GEM5 pull request #201
Opened 2024-11-07 18:13 UTC by zybzzz

related roadmap: #188 

This PR is solely intended to track code related to value prediction and does not currently need to be merged into xs-dev.

**Implemented features in the current code:**

1. Modified the o3 CPU architecture to support value prediction.
2. Designed a basic interface for the value predictor and implemented a simple Estride value predictor.
3. Configured related parameters for Estride, including the number of bits saved for stride and the size of the inflight window, allowing for basic design space exploration.

**Known issues:**

1. When modifying o3 CPU, I directly obtained the value prediction for instructions in the rename stage. Although this does not affect processor operation, the value predictor **loses an inflight window of fetch width + decode width**. In the future, the value predictor should be moved to the fetch stage.
2. Estride contains numerous assertions that check the width of basic numeric types. When using fixed-length types like int32_t, these checks are unnecessary. Future work will involve **changing types such as int to int32_t**.
3. The current Estride update strategy is still very basic. **A new update strategy based on instruction execution time is needed**, aligning with the original Estride design.
4. **Add declarations for code references**. The interface design and references in the code are based on the open-source code from cvp 1st, and relevant acknowledgments need to be included.

spec benchmark scoring is still ongoing.

2024-11-08 06:43 UTC, shinezyy requested changes

2024-11-08 06:43 UTC, shinezyy commented on src/cpu/o3/cpu.cc
> +            fprintf(stderr, "commit %lu insts\n", thread[tid]->numInst);
We always prefer DPRINTF rather than fprintf in GEM5

2024-11-08 06:43 UTC, shinezyy commented on src/cpu/valuepred/enhanced_stride.cc
> +        indexMarker += " ";
I'm not sure how such string operation affect performance. If performance is degraded, I suggest to put strong operations into if block like  `if (debug::xxx) {indexMarker = `

2024-11-08 06:49 UTC, shinezyy commented
- Did you provide some method to turn off the value predictor?
- If possible, you can provide a preliminary result.

2024-11-08 14:18 UTC, zybzzz commented
> * Did you provide some method to turn off the value predictor?
> * If possible, you can provide a preliminary result.

I don't have a way to turn off the value predictor yet, the only way to turn off the value predictor right now is to checkout to xs-dev and turn off the value predictor by changing the branch to cancel the value predictor related changes.

I think eventually I'll implement turning off the value predictor in code.

2024-11-15 05:41 UTC, zybzzz commented on src/cpu/o3/cpu.cc
> +            fprintf(stderr, "commit %lu insts\n", thread[tid]->numInst);
I've fixed the problem with this part of the code and I'll start running the scores after I get **issue1** finished.

2024-11-15 05:42 UTC, zybzzz commented on src/cpu/valuepred/enhanced_stride.cc
> +        indexMarker += " ";
I've fixed the problem with this part of the code and I'll start running the scores after I get **issue1** finished.

2025-02-20 14:19 UTC, closed without merging