cpu-o3: add perfCCT frame, add inst lifetime counter
OpenXiangShan/GEM5 pull request #206
Opened 2024-11-18 10:40 UTC by tastynoob

2024-11-19 06:12 UTC, jueshiwenli commented on src/cpu/o3/commit.cc
> -        DPRINTF(O3PipeView, "Record commit for inst sn:%lu, commitTick=%lu\n",
It is better to keep o3pipview.

2024-11-19 07:46 UTC, shinezyy requested changes

2024-11-19 07:46 UTC, shinezyy commented on src/cpu/o3/perfCCT.hh
> +        InvalidPos
Can we define this in Python's enumeration and use it when create SLQ table to avoid redundant code?

2024-11-27 03:16 UTC, jueshiwenli approved these changes

2024-11-28 01:39 UTC, jueshiwenli approved these changes

2024-11-30 02:47 UTC, shinezyy approved these changes
Redudant codes are now removed, excellent!

2024-11-30 03:27 UTC, merged

2024-12-02 07:21 UTC, dzwduan commented
Why not consider using https://github.com/shioyadan/Konata for pipeline visualization ?