cpu-o3: add `--disable-sc` param and fix a Segmentation Fault
OpenXiangShan/GEM5 pull request #212
Opened 2024-11-26 08:24 UTC by Lawrence-ID

* add `--disable-sc` command line parameter to disable SC.
* Fix segmentation fault when using `--enable-bp-db tage` with `enableSC=true`

2024-11-30 02:54 UTC, shinezyy requested changes

2024-11-30 02:54 UTC, shinezyy commented on configs/example/fs.py
> +                    test_sys.cpu[i].branchPred.tage.enableSC = (not args.disable_sc)
Why parentheses around "not args...."

2024-11-30 02:54 UTC, shinezyy commented on configs/example/xiangshan.py
> +            test_sys.cpu[i].branchPred.tage.enableSC = (not args.disable_sc)
Why parentheses around "not args...."?

2024-12-11 06:46 UTC, jensen-yan commented on configs/common/Options.py
> +                        help="enable sc (only for ftb branch predictor)")
maybe we should use --enable-sc, not --disable-sc, help= "enable sc(for tage predictor)", this code writing style is more unified.

2024-12-11 06:54 UTC, jensen-yan approved these changes

2024-12-11 09:38 UTC, shinezyy approved these changes

2024-12-11 09:54 UTC, merged